name: RDP

on:
  workflow_dispatch:

jobs:
  secure-rdp:
    runs-on: windows-latest
    timeout-minutes: 3600

    steps:
      - name: Configure Core RDP Settings
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' `
                             -Name "fDenyTSConnections" -Value 0 -Force
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' `
                             -Name "UserAuthentication" -Value 0 -Force
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' `
                             -Name "SecurityLayer" -Value 0 -Force

          netsh advfirewall firewall delete rule name="RDP-Tailscale"
          netsh advfirewall firewall add rule name="RDP-Tailscale" `
            dir=in action=allow protocol=TCP localport=3389

          Restart-Service -Name TermService -Force

      - name: Create Custom RDP User
        run: |
          $password = "KepangJaya!2025"
          $securePass = ConvertTo-SecureString $password -AsPlainText -Force
          New-LocalUser -Name "kepangjaya" -Password $securePass -AccountNeverExpires
          Add-LocalGroupMember -Group "Administrators" -Member "kepangjaya"
          Add-LocalGroupMember -Group "Remote Desktop Users" -Member "kepangjaya"
          
          echo "RDP_CREDS=User: kepangjaya | Password: $password" >> $env:GITHUB_ENV

      - name: Install Tailscale (with size check)
        run: |
          $tsUrl = "https://pkgs.tailscale.com/stable/tailscale-setup-1.82.0-amd64.msi"
          $installerPath = "$env:TEMP\tailscale.msi"
          
          Invoke-WebRequest -Uri $tsUrl -OutFile $installerPath

          $fileSizeMB = (Get-Item $installerPath).Length / 1MB
          if ($fileSizeMB -gt 50) {
              Write-Error "Installer terlalu besar ($fileSizeMB MB). Abort."
              exit 1
          }

          Start-Process msiexec.exe -ArgumentList "/i", "`"$installerPath`"", "/quiet", "/norestart" -Wait
          Remove-Item $installerPath -Force

      - name: Establish Tailscale Connection
        run: |
          & "$env:ProgramFiles\Tailscale\tailscale.exe" up --authkey=${{ secrets.TAILSCALE_AUTH_KEY }} --hostname="kepang-jaya"
          
          $tsIP = $null
          $retries = 0
          while (-not $tsIP -and $retries -lt 10) {
              $tsIP = & "$env:ProgramFiles\Tailscale\tailscale.exe" ip -4 
              Start-Sleep -Seconds 5
              $retries++
          }
          
          if (-not $tsIP) {
              Write-Error "Tailscale IP not assigned. Exiting."
              exit 1
          }
          echo "TAILSCALE_IP=$tsIP" >> $env:GITHUB_ENV

      - name: Verify RDP Accessibility
        run: |
          Write-Host "Tailscale IP: $env:TAILSCALE_IP"
          $testResult = Test-NetConnection -ComputerName $env:TAILSCALE_IP -Port 3389
          if (-not $testResult.TcpTestSucceeded) {
              Write-Error "TCP connection to RDP port 3389 failed"
              exit 1
          }
          Write-Host "TCP connectivity successful!"

      - name: Maintain Connection with Chaos Banner
        run: |
          Write-Host @"
╔══════════════════════════════════════╗
║   KEPANG JAYA UNDERGROUND - ACTIVE  ║
╠══════════════════════════════════════╣
║ Hostname : kepang-jaya              ║
║ User     : kepangjaya               ║
║ IP       : $env:TAILSCALE_IP        ║
║ Status   : RDP Tunnel Established   ║
╚══════════════════════════════════════╝
"@

          Write-Host "whoami spoof: kepangjaya@underground-node"
          Write-Host "System identity masked for performance mode"
          Write-Host "`n=== RDP ACCESS ==="
          Write-Host "Address: $env:TAILSCALE_IP"
          Write-Host "Username: kepangjaya"
          Write-Host "Password: KepangJaya!2025"
          Write-Host "==================`n"

          while ($true) {
              Write-Host "[$(Get-Date)] KepangJaya RDP Active - Use Ctrl+C to terminate"
              Start-Sleep -Seconds 300
          }
